name: "Generate Release Notes"
description: "Generate release notes by tag via Github's Rest APIs"
inputs:
  token:
    description: "GitHub token"
    required: true
  tag:
    description: "Tag for the release"
    required: true
  owner:
    description: "Owner of the repository"
    required: true
  repo:
    description: "Name of the repository"
    required: true
outputs:
  release: # id of output
    description: "Release result"
runs:
  using: "node20"
  main: "index.js"
